extends: "spectral:oas"

# Apply to both 3.0 and 3.1 specs
formats:
  - oas3
  - oas3_1

rules:
  # Quiet non-critical noise for Phase 4
  info-contact: off
  operation-success-response: warn
  no-$ref-siblings: warn
  oas3-schema: warn
