extends: "spectral:oas"
rules:
  # relax a few noisy rules for Phase 4
  info-contact: off
  operation-success-response: warn
  no-$ref-siblings: warn
  no-unused-components: warn
  oas3-schema: warn
