openapi: 3.0.3
info:
  title: phpGRC Audits API (stub)
  version: 0.1.0
paths:
  /api/audits/health:
    get:
      summary: Audits health probe (stub)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
