name: Actionlint

on:
  pull_request:
    paths: [ ".github/workflows/**" ]
  push:
    branches: [ main ]
    paths: [ ".github/workflows/**" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install actionlint (script, pinned with fallback)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .bin
          curl -fsSL -o .bin/download-actionlint.bash \
            https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash
          # Try pinned version first; fall back to latest if unavailable.
          bash .bin/download-actionlint.bash 1.7.1 .bin || \
          bash .bin/download-actionlint.bash latest .bin
          ./.bin/actionlint --version

      - name: Run actionlint
        shell: bash
        run: ./.bin/actionlint -color
