name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - "web/**"
      - "docs/api/**"
      - "docs/db/**"
      - "scripts/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "api/**"
      - "web/**"
      - "docs/api/**"
      - "docs/db/**"
      - "scripts/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  spectral:
    name: Spectral lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with: { node-version: "20" }
      - run: npx -y @stoplight/spectral-cli@6 lint docs/api/openapi.yaml -r .spectral.yaml

  openapi:
    name: OpenAPI lint
    runs-on: self-hosted
    needs: [spectral]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with: { node-version: "20" }
      - run: npx -y @redocly/cli@1.29.0 lint docs/api/openapi.yaml

  openapi_breaking:
    name: OpenAPI breaking-change gate
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    needs: [openapi]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: cp docs/api/openapi.yaml openapi.new.yaml
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base
      - id: check
        shell: bash
        run: |
          if [ -f base/docs/api/openapi.yaml ]; then
            echo "skip=false" >> "$GITHUB_OUTPUT"
            cp base/docs/api/openapi.yaml openapi.old.yaml
          else
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - if: steps.check.outputs.skip != 'true'
        run: |
          docker run --rm -v "$PWD":/spec openapitools/openapi-diff:2.1.0 \
            /spec/openapi.old.yaml /spec/openapi.new.yaml \
            --fail-on-incompatible \
            --html /spec/openapi-diff.html
      - if: steps.check.outputs.skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: openapi-diff-report
          path: openapi-diff.html

  schema_docs:
    name: Schema docs drift + linter
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
      - name: Make scripts executable
        run: chmod +x scripts/check-migration-doc-drift.sh
      - name: Check migration/doc drift
        env:
          BASE_REF: ${{ github.base_ref }}
        run: ./scripts/check-migration-doc-drift.sh
      - name: Lint schema doc against migrations
        run: php scripts/lint-schema-doc.php

  api_static:
    name: API static checks + audit
    runs-on: self-hosted
    needs: [openapi, schema_docs]
    defaults: { run: { working-directory: api } }
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_mysql, dom, xml, pcntl, posix, bcmath, fileinfo, sqlite3, pdo_sqlite
          coverage: none
          tools: composer:v2
      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer validate
        run: composer validate --strict --no-check-publish
      - name: Install deps (including dev tools)
        env:
          COMPOSER_NO_DEV: "0"
        run: COMPOSER_NO_DEV=0 composer install --no-interaction --prefer-dist
      - run: vendor/bin/pint -v
      - run: vendor/bin/phpstan analyse --level=10 --error-format=github --no-progress --memory-limit=-1
      - name: Generate app key for static analysis
        run: |
          KEY=$(php -r "echo 'base64:'.base64_encode(random_bytes(32));")
          SQLITE_DB="$GITHUB_WORKSPACE/api/database/psalm.sqlite"
          mkdir -p "$GITHUB_WORKSPACE/api/database"
          : > "$SQLITE_DB"
          {
            echo "APP_ENV=local"
            echo "APP_DEBUG=false"
            echo "APP_KEY=$KEY"
            echo "APP_URL=http://localhost"
            echo "APP_NAME=phpGRC"
            echo "CACHE_DRIVER=array"
            echo "SESSION_DRIVER=array"
            echo "QUEUE_CONNECTION=sync"
            echo "DB_CONNECTION=sqlite"
            echo "DB_DATABASE=$SQLITE_DB"
            echo "APP_BASE_PATH=$GITHUB_WORKSPACE/api"
          } >> "$GITHUB_ENV"
          {
            echo "APP_ENV=local"
            echo "APP_DEBUG=false"
            echo "APP_KEY=$KEY"
            echo "APP_URL=http://localhost"
            echo "APP_NAME=phpGRC"
            echo "CACHE_DRIVER=array"
            echo "SESSION_DRIVER=array"
            echo "QUEUE_CONNECTION=sync"
            echo "DB_CONNECTION=sqlite"
            echo "DB_DATABASE=$SQLITE_DB"
            echo "APP_BASE_PATH=$GITHUB_WORKSPACE/api"
          } > .env
      - name: Prepare Laravel storage
        run: |
          mkdir -p bootstrap/cache \
            storage/app storage/framework/cache storage/framework/sessions storage/framework/views \
            storage/logs storage/framework/testing/disks/local/exports
          :> storage/logs/laravel.log
      - name: Bootstrap Laravel (sanity check)
        run: |
          php -r 'require "vendor/autoload.php"; $app = require "bootstrap/app.php"; $app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();'
      - name: Psalm
        run: composer psalm -- --no-cache --long-progress
      - name: Clear generated app key
        if: always()
        run: |
          rm -f .env
          {
            echo "APP_ENV="
            echo "APP_DEBUG="
            echo "APP_KEY="
            echo "APP_URL="
            echo "APP_NAME="
            echo "CACHE_DRIVER="
            echo "SESSION_DRIVER="
            echo "QUEUE_CONNECTION="
            echo "DB_CONNECTION="
            echo "DB_DATABASE="
            echo "APP_BASE_PATH="
          } >> "$GITHUB_ENV"
      - name: Composer audit (prod only)
        run: composer audit --locked --no-dev

  api_mysql:
    name: API tests (MySQL, PHP 8.3) + coverage
    runs-on: self-hosted
    needs: [openapi, schema_docs]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: phpgrc_test
          MYSQL_USER: phpgrc
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports: [ "3307:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -uroot -psecret"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30
    defaults: { run: { working-directory: api } }
    steps:
      - name: Docker preflight
        run: docker info
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_mysql
          coverage: xdebug
          tools: composer:v2
      - name: Resolve lockfile (sync with composer.json)
        run: composer update --no-interaction --prefer-dist --no-progress --prefer-stable
      - run: composer install --no-interaction --prefer-dist
      - name: Wait for MySQL (PDO probe)
        shell: bash
        run: |
          for i in {1..60}; do
            php -r 'try{$pdo=new PDO("mysql:host=127.0.0.1;port=3307","root","secret",[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);exit(0);}catch(Throwable $e){exit(1);}'; ec=$?
            if [ $ec -eq 0 ]; then echo "MySQL ready"; break; fi
            sleep 1
          done
      - name: Write .env.testing (MySQL)
        run: |
          cat > .env.testing <<'EOF'
          APP_ENV=testing
          APP_DEBUG=false
          APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3307
          DB_DATABASE=phpgrc_test
          DB_USERNAME=phpgrc
          DB_PASSWORD=secret
          CACHE_DRIVER=array
          CACHE_STORE=array
          SESSION_DRIVER=array
          QUEUE_CONNECTION=sync
          FILESYSTEM_DISK=local
          EOF
      - name: Prepare Laravel dirs
        run: |
          mkdir -p bootstrap/cache \
            storage/app storage/framework/cache storage/framework/sessions storage/framework/views \
            storage/logs
          :> storage/logs/laravel.log
          :> storage/setup-config.php
      - name: Migrate schema
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: phpgrc_test
          DB_USERNAME: phpgrc
          DB_PASSWORD: secret
          CORE_SETUP_ENABLED: "true"
          CORE_SETUP_SHARED_CONFIG_PATH: "${{ github.workspace }}/api/storage/setup-config.php"
        run: |
          php artisan config:clear
          php artisan migrate --force
      - name: PHPUnit (full)
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: phpgrc_test
          DB_USERNAME: phpgrc
          DB_PASSWORD: secret
          CORE_SETUP_ENABLED: "true"
          CORE_SETUP_SHARED_CONFIG_PATH: "${{ github.workspace }}/api/storage/setup-config.php"
          XDEBUG_MODE: coverage
        run: |
          vendor/bin/phpunit --log-junit junit.xml \
            --coverage-clover coverage.xml \
            --coverage-filter app
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-mysql-8.3
          path: |
            api/junit.xml
            api/coverage.xml
            api/storage/logs/*.log

  web:
    name: Web build + tests + coverage + audit
    runs-on: self-hosted
    needs: [openapi]
    defaults: { run: { working-directory: web } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: web/package-lock.json
      - name: Validate npm lockfile generated on Linux
        shell: bash
        run: |
          npm install --package-lock-only --ignore-scripts
          if ! git diff --quiet package-lock.json; then
            echo '::error::web/package-lock.json must be generated on Linux. Run `npm install --package-lock-only` on Linux and commit the updated lockfile.'
            git diff package-lock.json
            exit 1
          fi
      - name: Install deps (auto-sync lock)
        shell: bash
        run: |
          set -e
          npm ci || { echo "::warning::package-lock.json out of date. Regenerating..."; npm install --package-lock-only; npm ci; }
      - name: ESLint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - run: npm run test:coverage
      - run: npm run build
      - run: npm audit --audit-level=high
      - uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-coverage
          path: web/coverage

