name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - "web/**"
      - "docs/api/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "api/**"
      - "web/**"
      - "docs/api/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  openapi:
    name: OpenAPI lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Lint spec with Redocly
        run: npx -y @redocly/cli@1.29.0 lint docs/api/openapi.yaml

  openapi_breaking:
    name: OpenAPI breaking-change gate
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    needs: [openapi]
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Save HEAD spec
        run: cp docs/api/openapi.yaml openapi.new.yaml

      - name: Checkout BASE
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - id: check
        name: Check base spec presence
        shell: bash
        run: |
          if [ -f base/docs/api/openapi.yaml ]; then
            echo "skip=false" >> "$GITHUB_OUTPUT"
            cp base/docs/api/openapi.yaml openapi.old.yaml
          else
            echo "Base spec not found. Skipping breaking-change check."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run openapi-diff
        if: steps.check.outputs.skip != 'true'
        run: |
          docker run --rm -v "$PWD":/spec openapitools/openapi-diff:2.0.0 \
            /spec/openapi.old.yaml /spec/openapi.new.yaml \
            --fail-on-incompatible \
            --html /spec/openapi-diff.html

      - name: Upload diff report
        if: steps.check.outputs.skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: openapi-diff-report
          path: openapi-diff.html

  api:
    name: API checks (SQLite + static analysis)
    runs-on: self-hosted
    needs: [openapi] # breaking-change gate runs only on PRs
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_mysql, pdo_sqlite, sqlite3, dom, xml, pcntl, posix, bcmath, fileinfo
          coverage: none
          tools: composer:v2

      - name: Assert parallel prerequisites
        run: |
          php -r 'echo "disable_functions=",ini_get("disable_functions"),PHP_EOL;'
          php -r 'echo "proc_open:",function_exists("proc_open")?"ok":"DISABLED",PHP_EOL;'
          php -r 'echo "pcntl:",extension_loaded("pcntl")?"on":"off",PHP_EOL;'

      - name: Prepare Laravel dirs
        run: |
          mkdir -p bootstrap/cache \
            storage/app \
            storage/framework/cache storage/framework/sessions storage/framework/views \
            storage/logs
          :> storage/logs/laravel.log

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --prefer-dist

      - name: Create SQLite testing DB and env
        run: |
          mkdir -p database
          :> database/database.testing.sqlite
          cat > .env.testing <<'EOF'
          APP_ENV=testing
          APP_DEBUG=false
          APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
          DB_CONNECTION=sqlite
          DB_DATABASE=${{ github.workspace }}/api/database/database.testing.sqlite
          CACHE_DRIVER=array
          SESSION_DRIVER=array
          QUEUE_CONNECTION=sync
          FILESYSTEM_DISK=local
          CORE_RBAC_ENABLED=false
          CORE_RBAC_REQUIRE_AUTH=false
          EOF

      - name: Pint
        run: vendor/bin/pint -v

      - name: PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Psalm
        env:
          APP_ENV: testing
          APP_DEBUG: "true"
          APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
          DB_CONNECTION: sqlite
          DB_DATABASE: ${{ github.workspace }}/api/database/database.testing.sqlite
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
        run: |
          THREADS=$(nproc --all || echo 4)
          vendor/bin/psalm --threads="$THREADS" --scan-threads="$THREADS" --no-diff --long-progress

      - name: Clear and cache config
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: PHPUnit
        run: vendor/bin/phpunit --log-junit junit.xml

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-artifacts
          path: |
            api/junit.xml
            api/storage/logs/*.log

  web:
    name: Web build (Vite)
    runs-on: self-hosted
    needs: [openapi]
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
