name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  api:
    name: API checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_mysql, dom, xml
          coverage: none

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('api/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --prefer-dist

      - name: Pint
        run: vendor/bin/pint -v

      - name: PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=-1

      - name: Psalm
        run: vendor/bin/psalm --no-cache

      - name: PHPUnit
        run: vendor/bin/phpunit
