name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # your runner on the server
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, fileinfo
          coverage: none

      - name: Composer install (prod)
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Stage release dir
        run: |
          set -euo pipefail
          RELEASE="/var/www/phpgrc/releases/${GITHUB_RUN_NUMBER}"
      
          # ensure target structure exists
          sudo mkdir -p "$RELEASE" \
            /var/www/phpgrc/shared/storage \
            /var/www/phpgrc/shared/bootstrap/cache
      
          # copy build to release
          sudo rsync -a --delete ./ "$RELEASE"/
      
          # link shared dirs
          cd "$RELEASE"
          sudo rm -rf storage bootstrap/cache
          sudo ln -sfn /var/www/phpgrc/shared/storage storage
          sudo ln -sfn /var/www/phpgrc/shared/bootstrap/cache bootstrap/cache
      
          # permissions
          sudo chown -R www-data:www-data /var/www/phpgrc
          sudo find /var/www/phpgrc/shared/storage -type d -exec chmod 775 {} \;
          sudo chmod 775 /var/www/phpgrc/shared/bootstrap/cache
      
          # write .env (edit secrets)
          sudo tee "$RELEASE/.env" >/dev/null <<'ENV'
          APP_ENV=production
          APP_DEBUG=false
          APP_URL=https://phpgrc.gruntlabs.net
          APP_KEY=${{ secrets.APP_KEY }}
          
          CACHE_STORE=file
          SESSION_DRIVER=file
          QUEUE_CONNECTION=sync
          
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASS }}
          
          SANCTUM_STATEFUL_DOMAINS=phpgrc.gruntlabs.net
          SESSION_DOMAIN=phpgrc.gruntlabs.net
          ENV
      
          # warmup
          sudo -u www-data php artisan key:generate --force || true
          sudo -u www-data php artisan storage:link || true
          sudo -u www-data php artisan migrate --force
          sudo -u www-data php artisan config:clear
          sudo -u www-data php artisan route:clear
          sudo -u www-data php artisan optimize
      
          # switch current & reload
          sudo ln -sfn "$RELEASE" /var/www/phpgrc/current
          sudo systemctl reload php8.3-fpm
          sudo systemctl reload apache2
      
