name: schema-drift

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  drift:
    runs-on: self-hosted

    services:
      mysql:
        image: mysql:8.0
        ports: [ "3307:3306" ]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: phpgrc_test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          extensions: pdo_mysql
          coverage: none

      - name: Install API dependencies
        working-directory: api
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          cp -n .env.example .env || true
          php artisan key:generate

      - name: Wait for MySQL (TCP check)
        run: |
          for i in {1..120}; do
            if (echo > /dev/tcp/127.0.0.1/3307) >/dev/null 2>&1; then exit 0; fi
            sleep 1
          done
          echo "MySQL not reachable on 127.0.0.1:3307"; exit 1

      - name: Reset and migrate database
        working-directory: api
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: phpgrc_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          php artisan migrate:fresh --force

      - name: Generate live schema doc
        working-directory: api
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: phpgrc_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          php scripts/schema_docgen.php > ../docs/db/schema.live.md

      - name: Normalize docs SCHEMA.md
        run: |
          php api/scripts/schema_normalize.php docs/db/SCHEMA.md > /tmp/schema.doc.norm

      - name: Normalize live schema
        run: |
          php api/scripts/schema_normalize.php docs/db/schema.live.md > /tmp/schema.live.norm

      - name: Diff normalized structures
        run: |
          set -e
          if ! diff -u /tmp/schema.doc.norm /tmp/schema.live.norm; then
            echo "::error ::Schema drift detected in structure. Update docs/db/SCHEMA.md (or migrations) to reconcile."
            exit 2
          fi

      - name: Upload artifacts (on drift)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: schema-artifacts
          path: |
            docs/db/schema.live.md
            /tmp/schema.doc.norm
            /tmp/schema.live.norm
