name: schema-drift

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  drift:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports: [ "3307:3306" ]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: phpgrc_test
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install API dependencies
        working-directory: api
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          cp -n .env.example .env || true
          php artisan key:generate

      - name: Wait for MySQL
        run: |
          for i in {1..60}; do
            if mysqladmin ping -h 127.0.0.1 -P3307 -uroot -proot --silent; then exit 0; fi
            sleep 1
          done
          echo "MySQL did not become ready"; exit 1

      - name: Reset and migrate database
        working-directory: api
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: phpgrc_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          php artisan migrate:fresh --force

      - name: Generate live schema doc
        working-directory: api
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3307
          DB_DATABASE: phpgrc_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          php scripts/schema_docgen.php > ../docs/db/schema.live.md

      - name: Prepare table-only sections
        run: |
          awk '/^## Tables/{flag=1} flag' docs/db/SCHEMA.md > /tmp/SCHEMA.tables.md
          awk '/^## Tables/{flag=1} flag' docs/db/schema.live.md > /tmp/schema.live.tables.md

      - name: Diff live vs committed schema (tables only)
        run: |
          set -e
          if ! diff -u /tmp/SCHEMA.tables.md /tmp/schema.live.tables.md; then
            echo "::error ::Schema drift detected in table structure. Update docs/db/SCHEMA.md to match current migrations."
            exit 2
          fi

      - name: Upload live schema (on drift)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: schema-live-md
          path: docs/db/schema.live.md
