name: web-ci

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/web-ci.yml"
  pull_request:
    paths:
      - "web/**"

jobs:
  build:
    runs-on: self-hosted
    defaults: { run: { working-directory: web } }
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (cached)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests + coverage
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: NPM audit (high+)
        run: npm audit --audit-level=high

      - name: Upload web coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-coverage
          path: coverage
